
INSERT INTO brincareducando.atividades (
    codigo_externo,
    titulo,
    descricao,
    categoria,
    energia,
    preparo_minutos,
    duracao_minutos,
    idade_min_meses,
    idade_max_meses,
    dificuldade,
    local,
    materiais,
    beneficios,
    passos,
    dicas
) VALUES 
(
        'atividade_001',
        'Pintura com gelo colorido',
        'Congele água com corante alimentício em forminhas. Bebê explora textura fria e cores em papel grande, desenvolvendo exploração sensorial tátil.',
        'sensorial',
        'media',
        30,
        10,
        6,
        12,
        'facil',
        'interno',
        ARRAY['Forminhas de gelo','Corante alimentício','Papel grande','Água'],
        ARRAY['Coordenação Motora','Exploração Sensorial','Percepção Visual'],
        ARRAY['Congele água com corante em forminhas de gelo','Coloque papel grande no chão ou mesa','Entregue o gelo colorido para o bebê explorar','Deixe ele deslizar o gelo no papel','Observe as reações de temperatura e cor'],
        ARRAY['Use corante alimentício natural','Supervisione para evitar ingestão','Temperatura fria estimula sensações novas']
    ),
(
        'atividade_002',
        'Sacola surpresa de tecidos',
        'Coloque tecidos de diferentes texturas em uma sacola. Bebê retira e explora cada um com as mãos e boca.',
        'sensorial',
        'baixa',
        5,
        10,
        0,
        6,
        'facil',
        'interno',
        ARRAY['Sacola de pano','3-4 retalhos de tecidos variados','Tecidos limpos e seguros'],
        ARRAY['Exploração Sensorial','Coordenação Motora','Atenção'],
        ARRAY['Selecione tecidos de texturas variadas (liso, áspero, macio)','Coloque na sacola','Apresente a sacola ao bebê','Deixe ele explorar livremente','Nomeie as texturas enquanto ele toca'],
        ARRAY['Certifique-se que os tecidos são seguros para levar à boca','Varie as texturas a cada sessão','Estimula desenvolvimento tátil precoce']
    ),
(
        'atividade_003',
        'Caixa de sons da cozinha',
        'Panelas, colheres e potes viram instrumentos musicais para explorar diferentes sons e ritmos.',
        'sensorial',
        'media',
        3,
        10,
        12,
        24,
        'facil',
        'interno',
        ARRAY['2-3 panelas','Colheres de pau','Potes plásticos'],
        ARRAY['Exploração Sensorial','Coordenação Motora','Ritmo'],
        ARRAY['Separe panelas e utensílios seguros','Coloque no chão ou mesa baixa','Mostre como bater para fazer sons','Deixe a criança explorar livremente','Faça ritmos simples para ela imitar'],
        ARRAY['Evite materiais que possam machucar','Crie ritmos alternados (rápido/lento)','Estimula discriminação auditiva']
    ),
(
        'atividade_004',
        'Tapete sensorial improvisado',
        'Cole texturas variadas em papelão grande para criança andar descalça e explorar diferentes sensações nos pés.',
        'sensorial',
        'media',
        15,
        10,
        12,
        36,
        'facil',
        'interno',
        ARRAY['Papelão grande','Texturas: lixa, tecido, plástico bolha','Fita adesiva'],
        ARRAY['Equilíbrio','Exploração Sensorial','Coordenação Motora'],
        ARRAY['Cole diferentes texturas no papelão','Coloque no chão de forma segura','Tire os sapatos da criança','Convide-a a caminhar sobre as texturas','Pergunte o que ela sente em cada uma'],
        ARRAY['Varie as texturas para enriquecer experiência','Use materiais seguros e limpos','Estimula propriocepção dos pés']
    ),
(
        'atividade_005',
        'Desenho gigante no papelão',
        'Use papelão grande no chão para criança desenhar com movimentos amplos, desenvolvendo coordenação motora grossa.',
        'criativa',
        'media',
        5,
        15,
        24,
        36,
        'facil',
        'interno',
        ARRAY['Papelão grande','Giz de cera grosso','Fita para fixar no chão'],
        ARRAY['Coordenação Motora','Expressão','Criatividade'],
        ARRAY['Fixe papelão grande no chão','Ofereça giz de cera','Incentive movimentos amplos','Deixe desenhar livremente','Pergunte sobre o desenho'],
        ARRAY['Movimentos amplos preparam para escrita','Não corrija o desenho','Celebre as tentativas']
    ),
(
        'atividade_006',
        'Desenho com água na varanda',
        'Use pincel e água para desenhar no chão ou parede externa. Desenhos evaporam e podem ser refeitos.',
        'criativa',
        'media',
        2,
        15,
        36,
        60,
        'facil',
        'ao ar livre',
        ARRAY['Pincel largo','Balde com água','Varanda ou calçada'],
        ARRAY['Coordenação Motora','Criatividade','Observação'],
        ARRAY['Encha balde com água','Dê pincel para criança','Mostre como desenhar no chão','Deixe ela criar livremente','Observe junto a água evaporando'],
        ARRAY['Atividade sem sujeira permanente','Ensina conceito de temporariedade','Ideal para dias quentes']
    ),
(
        'atividade_007',
        'Pintura com esponja e prato',
        'Corte esponja em pedaços e use como carimbos com tinta lavável em prato raso.',
        'criativa',
        'media',
        5,
        15,
        12,
        24,
        'facil',
        'interno',
        ARRAY['Esponja','Tinta lavável','Papel','Prato raso'],
        ARRAY['Coordenação Motora','Criatividade','Exploração Sensorial'],
        ARRAY['Corte esponja em pedaços pequenos','Coloque tinta no prato','Mostre como carimbar','Deixe a criança explorar','Faça padrões simples'],
        ARRAY['Prefira tintas atóxicas','Textura da esponja estimula tato','Desenvolve pinça de três dedos']
    ),
(
        'atividade_008',
        'Escultura de papel amassado',
        'Amassar papel e moldar formas simples desenvolve força nas mãos e criatividade tridimensional.',
        'criativa',
        'baixa',
        2,
        15,
        36,
        60,
        'facil',
        'interno',
        ARRAY['Papel de rascunho','Fita adesiva (opcional)'],
        ARRAY['Força','Criatividade','Coordenação Motora'],
        ARRAY['Dê folhas de papel para criança','Mostre como amassar','Incentive criar bolas, cobrinhas','Use fita para unir partes se quiser','Converse sobre as formas criadas'],
        ARRAY['Fortalece músculos das mãos','Não precisa ser perfeito','Estimula imaginação tridimensional']
    ),
(
        'atividade_009',
        'Torre de potes e panelas',
        'Empilhar potes e panelas de tamanhos diferentes desenvolve noção espacial e coordenação.',
        'criativa',
        'media',
        3,
        15,
        12,
        36,
        'facil',
        'interno',
        ARRAY['3-4 potes de tamanhos diferentes','Panelas plásticas'],
        ARRAY['Coordenação Motora','Raciocínio Lógico','Equilíbrio'],
        ARRAY['Separe potes de tamanhos variados','Mostre como empilhar','Deixe a criança tentar','Comemore quando conseguir','Aumente o desafio com mais peças'],
        ARRAY['Usar diferentes tamanhos ensina sequência','Quedas são parte do aprendizado','Marco Montessori de empilhamento']
    ),
(
        'atividade_010',
        'Cidade de caixas',
        'Caixas de papelão viram casas, carros e prédios para brincadeira simbólica e construção criativa.',
        'criativa',
        'media',
        10,
        30,
        36,
        60,
        'medio',
        'interno',
        ARRAY['2-3 caixas de papelão','Canetinha','Fita adesiva'],
        ARRAY['Imaginação','Criatividade','Brincadeira Simbólica'],
        ARRAY['Separe caixas de tamanhos variados','Deixe criança decorar com canetinha','Ajude a criar portas e janelas','Monte a cidade juntos','Brinque de faz-de-conta'],
        ARRAY['Criança define o que cada caixa é','Não precisa ser realista','Estimula narrativa e imaginação']
    ),
(
        'atividade_011',
        'Caça aos pares na gaveta de meias',
        'Encontrar meias iguais e parear desenvolve discriminação visual e conceito de correspondência.',
        'cognitiva',
        'baixa',
        2,
        10,
        12,
        24,
        'facil',
        'interno',
        ARRAY['3-4 pares de meias'],
        ARRAY['Foco','Raciocínio Lógico','Classificação'],
        ARRAY['Separe alguns pares de meias','Misture todas','Pegue uma e peça para achar o par','Comemore quando encontrar','Repita com outras meias'],
        ARRAY['Comece com meias bem diferentes','Atividade Montessori de vida prática','Ensina correspondência um-a-um']
    ),
(
        'atividade_012',
        'Classificar tampas por tamanho',
        'Organizar tampas do menor ao maior desenvolve seriação e percepção de tamanhos.',
        'cognitiva',
        'baixa',
        3,
        10,
        24,
        36,
        'facil',
        'interno',
        ARRAY['4-5 tampas de diferentes tamanhos'],
        ARRAY['Raciocínio Lógico','Classificação','Percepção Visual'],
        ARRAY['Separe tampas de tamanhos variados','Mostre a menor e a maior','Peça para colocar em ordem','Ajude se necessário','Use palavras: pequeno, médio, grande'],
        ARRAY['Comece com 3 tampas','Material sensorial Montessori','Prepara para conceitos matemáticos']
    ),
(
        'atividade_013',
        'Organizar talheres da família',
        'Separar garfos, facas e colheres no porta-talheres é vida prática que desenvolve classificação.',
        'cognitiva',
        'baixa',
        2,
        10,
        36,
        60,
        'medio',
        'interno',
        ARRAY['Talheres limpos','Porta-talheres'],
        ARRAY['Classificação','Colaboração','Autonomia'],
        ARRAY['Tire talheres do porta-talheres','Peça para separar por tipo','Nomeie cada utensílio','Deixe ela organizar','Agradeça pela ajuda'],
        ARRAY['Atividade Montessori de vida prática','Integra criança nas tarefas','Desenvolve senso de utilidade']
    ),
(
        'atividade_014',
        'Labirinto de caixa de papelão',
        'Criar labirinto simples com obstáculos para bola ou carrinho desenvolve resolução de problemas.',
        'cognitiva',
        'media',
        10,
        15,
        24,
        36,
        'medio',
        'interno',
        ARRAY['Caixa de sapato','Canudos ou palitos','Fita','Bolinha'],
        ARRAY['Raciocínio Lógico','Coordenação Motora','Planejamento'],
        ARRAY['Cole canudos dentro da caixa criando caminhos','Coloque bolinha na entrada','Peça para criança inclinar caixa','Objetivo: levar bolinha até o fim','Comemore quando conseguir'],
        ARRAY['Comece com caminho simples','Estimula funções executivas','Pode aumentar complexidade']
    ),
(
        'atividade_015',
        'Resolver qual pote cabe onde',
        'Encaixar potes de diferentes tamanhos uns nos outros desenvolve percepção espacial.',
        'cognitiva',
        'baixa',
        2,
        10,
        12,
        24,
        'facil',
        'interno',
        ARRAY['3-4 potes que encaixam'],
        ARRAY['Raciocínio Lógico','Coordenação Motora','Percepção Espacial'],
        ARRAY['Separe potes que encaixam','Tire todos de dentro','Mostre como encaixar um no outro','Deixe criança tentar','Incentive tentativa e erro'],
        ARRAY['Não corrija imediatamente','Descoberta pelo erro é aprendizado','Estimula persistência']
    ),
(
        'atividade_016',
        'Missão de entregar recados pela casa',
        'Dar tarefas simples como levar objeto de um cômodo a outro desenvolve memória de trabalho.',
        'cognitiva',
        'media',
        1,
        10,
        36,
        60,
        'medio',
        'interno',
        ARRAY['Objetos da casa'],
        ARRAY['Memória','Autonomia','Foco'],
        ARRAY['Escolha objeto simples (colher, pano)','Peça: ''Leve isso para a cozinha''','Aguarde ela ir e voltar','Comemore quando completar','Aumente distância gradualmente'],
        ARRAY['Comece com instruções curtas','Desenvolve memória de trabalho','Integra criança na rotina']
    ),
(
        'atividade_017',
        'Jogo da bandeja que some',
        'Mostre objetos em bandeja, cubra, retire um e peça para descobrir qual sumiu.',
        'cognitiva',
        'baixa',
        3,
        10,
        24,
        36,
        'facil',
        'interno',
        ARRAY['Bandeja','3-4 objetos pequenos','Pano'],
        ARRAY['Memória','Foco','Observação'],
        ARRAY['Coloque 3 objetos na bandeja','Deixe criança observar bem','Cubra com pano','Retire um objeto escondido','Descubra e pergunte o que sumiu'],
        ARRAY['Comece com 3 objetos bem diferentes','Jogo clássico de memória visual','Aumente quantidade gradualmente']
    ),
(
        'atividade_018',
        'Caminho de obstáculos com cadeiras',
        'Criar circuito com almofadas e cadeiras para criança passar por baixo, pular e contornar.',
        'movimento',
        'alta',
        5,
        15,
        24,
        36,
        'facil',
        'interno',
        ARRAY['2 cadeiras','Almofadas','Espaço livre'],
        ARRAY['Equilíbrio','Coordenação Motora','Agilidade'],
        ARRAY['Organize cadeiras e almofadas no chão','Mostre o caminho','Peça para passar por baixo da cadeira','Pular almofadas','Comemore ao completar'],
        ARRAY['Supervisione para segurança','Varie obstáculos','Atividade física OMS recomendada']
    ),
(
        'atividade_019',
        'Dança das estátuas na sala',
        'Música toca, todos dançam. Música para, todos congelam como estátua.',
        'movimento',
        'alta',
        1,
        10,
        36,
        60,
        'facil',
        'interno',
        ARRAY['Celular com música'],
        ARRAY['Autorregulação','Coordenação Motora','Ritmo'],
        ARRAY['Coloque música animada','Dance junto com a criança','Pause a música subitamente','Todos congelam como estátua','Retome música e repita'],
        ARRAY['Desenvolve autocontrole motor','Estimula escuta ativa','Gasta energia de forma divertida']
    ),
(
        'atividade_020',
        'Transferir água com esponja',
        'Duas tigelas, uma com água. Criança transfere água usando esponja, desenvolvendo coordenação fina.',
        'movimento',
        'baixa',
        3,
        15,
        24,
        36,
        'facil',
        'interno',
        ARRAY['2 tigelas','Esponja','Água','Pano para secar'],
        ARRAY['Coordenação Motora','Foco','Autonomia'],
        ARRAY['Coloque água colorida em uma tigela','Tigela vazia ao lado','Dê esponja para criança','Mostre como molhar e espremer','Deixe ela transferir a água'],
        ARRAY['Atividade Montessori clássica','Movimento de pinça essencial','Prepara para escrita']
    ),
(
        'atividade_021',
        'Histórias do dia com panelas',
        'Usar panelas e utensílios como personagens para criar histórias inventadas juntos.',
        'criativa',
        'baixa',
        2,
        15,
        36,
        60,
        'facil',
        'interno',
        ARRAY['2-3 panelas','Colher de pau','Pano de prato'],
        ARRAY['Linguagem','Imaginação','Vínculo Familiar'],
        ARRAY['Apresente panelas como personagens','Dê nomes: panela mãe, colher filha','Comece história simples','Pare e peça criança continuar','Use objetos para representar ações'],
        ARRAY['Não corrija gramática durante história','Foco na fluidez da fala','Promove consciência narrativa']
    ),
(
        'atividade_022',
        'Rimas com nomes da família',
        'Brincar de criar rimas bobas com nomes conhecidos desenvolve consciência fonológica.',
        'criativa',
        'baixa',
        1,
        10,
        48,
        72,
        'medio',
        'interno',
        ARRAY['Nenhum material necessário'],
        ARRAY['Linguagem','Consciência Fonológica','Vínculo Familiar'],
        ARRAY['Fale nomes da família devagar','Crie rima boba: Ana-banana','Explique o jogo','Convide criança a inventar rimas','Não force rimas perfeitas'],
        ARRAY['Valorize aproximações sonoras','Comece com nomes curtos','Fortemente associado à alfabetização']
    ),
(
        'atividade_023',
        'Caça às letras do próprio nome',
        'Esconder letras do nome pela casa para criança encontrar e montar em sequência.',
        'cognitiva',
        'media',
        5,
        15,
        48,
        72,
        'medio',
        'interno',
        ARRAY['Papéis com letras','Fita crepe'],
        ARRAY['Linguagem','Memória','Autoconfiança'],
        ARRAY['Escreva cada letra do nome em papel','Cole em locais visíveis','Mostre modelo do nome completo','Peça criança caçar as letras','Monte nome na ordem juntos'],
        ARRAY['Nome próprio é porta de entrada para leitura','Não corrija inversões com rigidez','Celebre reconhecimento das letras']
    ),
(
        'atividade_024',
        'Histórias em sequência com fotos',
        'Usar fotos do dia ou passeio para criar narrativa com começo, meio e fim.',
        'criativa',
        'baixa',
        5,
        15,
        60,
        96,
        'medio',
        'interno',
        ARRAY['3-4 fotos impressas ou no celular'],
        ARRAY['Linguagem','Memória','Organização Temporal'],
        ARRAY['Selecione fotos de evento recente','Misture ordem das fotos','Peça criança colocar em ordem','Conte história baseada nas fotos','Use palavras: primeiro, depois, por fim'],
        ARRAY['Desenvolve estrutura narrativa','Fortalece memória episódica','Base para produção textual futura']
    ),
(
        'atividade_025',
        'Caixa de sons caseira',
        'undefined',
        'sensorial',
        'baixa',
        10,
        10,
        12,
        36,
        'facil',
        'interno',
        ARRAY['3-4 potes plásticos com tampa','Arroz, feijão, botões'],
        ARRAY['Exploração Sensorial','Ritmo','Discriminação Auditiva'],
        ARRAY['Coloque materiais diferentes em cada pote','Feche bem as tampas','Deixe criança chacoalhar','Compare sons: qual é mais alto?','Crie ritmos simples'],
        ARRAY['Certifique tampas bem fechadas','Material Montessori sensorial','Estimula discriminação de timbres']
    ),
(
        'atividade_026',
        'Cantigas com gestos no colo',
        'Cantar músicas simples fazendo gestos e movimentos com bebê no colo.',
        'criativa',
        'baixa',
        0,
        10,
        0,
        12,
        'facil',
        'interno',
        ARRAY['Nenhum'],
        ARRAY['Vínculo Familiar','Linguagem','Ritmo'],
        ARRAY['Sente confortavelmente com bebê','Cante cantiga conhecida','Faça gestos suaves (palmas, balançar)','Olhe nos olhos do bebê','Repita música favorita'],
        ARRAY['Cantar desenvolve linguagem precoce','Ritmo e melodia acalmam','Fortalece vínculo afetivo']
    ),
(
        'atividade_027',
        'Histórias olhando livro ao contrário',
        'Deixar criança segurar livro infantil e inventar história pelas imagens, sem ler texto.',
        'criativa',
        'baixa',
        1,
        10,
        24,
        36,
        'facil',
        'interno',
        ARRAY['Livro infantil com imagens'],
        ARRAY['Linguagem','Imaginação','Pré-leitura'],
        ARRAY['Dê livro para criança segurar','Deixe ela virar páginas','Pergunte: o que está acontecendo?','Não corrija interpretações','Valorize narrativa dela'],
        ARRAY['Leitura de imagens é base para alfabetização','Criança como protagonista da história','Desenvolve oralidade']
    ),
(
        'atividade_028',
        'Desenhar o som',
        'Ouvir sons diferentes (palmas, bater panela) e desenhar como imagina que seria o som.',
        'criativa',
        'baixa',
        3,
        15,
        60,
        96,
        'medio',
        'interno',
        ARRAY['Papel','Lápis de cor','Fonte de sons'],
        ARRAY['Expressão','Criatividade','Sinestesia'],
        ARRAY['Faça som (palma, sino, bater colher)','Peça criança desenhar o som','Pergunte: que cor tem esse som?','Repita com sons diferentes','Converse sobre os desenhos'],
        ARRAY['Não há certo ou errado','Estimula correspondência sensorial','Desenvolve expressão abstrata']
    ),
(
        'atividade_029',
        'Rolando garrafa de água pelo caminho',
        'Criar caminho com fita no chão e criança rola garrafa plástica tentando seguir a linha.',
        'movimento',
        'media',
        5,
        10,
        12,
        24,
        'facil',
        'interno',
        ARRAY['Garrafa plástica','Fita crepe'],
        ARRAY['Coordenação Motora','Foco','Controle de Força'],
        ARRAY['Cole fita fazendo caminho no chão','Dê garrafa para criança','Mostre como rolar seguindo linha','Incentive manter na linha','Comemore quando completar'],
        ARRAY['Desenvolve controle motor fino','Pode fazer caminhos curvos','Estimula persistência']
    ),
(
        'atividade_030',
        'Pular de almofada em almofada',
        'Espalhar almofadas no chão como pedras de rio para criança pular sem tocar o chão.',
        'movimento',
        'alta',
        3,
        10,
        36,
        60,
        'facil',
        'interno',
        ARRAY['4-5 almofadas'],
        ARRAY['Equilíbrio','Agilidade','Coordenação Motora'],
        ARRAY['Espalhe almofadas pelo chão','Explique: chão é rio, almofadas são pedras','Criança pula de uma em outra','Varie distâncias entre almofadas','Aumente desafio gradualmente'],
        ARRAY['Supervisione para segurança','Desenvolve saltos e equilíbrio','Imaginação transforma exercício em jogo']
    ),
(
        'atividade_031',
        'Enfiar macarrão no escorredor',
        'Pegar macarrão cru e enfiar nos furos do escorredor desenvolve precisão motora fina.',
        'movimento',
        'baixa',
        2,
        15,
        24,
        36,
        'facil',
        'interno',
        ARRAY['Macarrão espaguete cru','Escorredor'],
        ARRAY['Coordenação Motora','Foco','Paciência'],
        ARRAY['Vire escorredor de cabeça para baixo','Dê macarrões para criança','Mostre como enfiar nos furos','Deixe ela fazer sozinha','Comemore cada macarrão inserido'],
        ARRAY['Atividade Montessori DIY','Treina pinça e precisão','Prepara para segurar lápis']
    ),
(
        'atividade_032',
        'Rasgar papel para chuva',
        'Rasgar papel em pedacinhos e jogar para cima como chuva de confete.',
        'movimento',
        'media',
        1,
        10,
        12,
        24,
        'facil',
        'interno',
        ARRAY['Papel de rascunho'],
        ARRAY['Coordenação Motora','Força','Expressão'],
        ARRAY['Dê folhas de papel','Mostre como rasgar','Deixe rasgar livremente','Juntem pedaços rasgados','Joguem para cima como confete'],
        ARRAY['Rasgar desenvolve força bilateral','Movimento de pinça essencial','Momento de limpar também é aprendizado']
    ),
(
        'atividade_033',
        'Colar feijão no contorno',
        'Desenhar forma simples e criança cola feijões seguindo a linha, desenvolvendo precisão.',
        'movimento',
        'baixa',
        5,
        20,
        36,
        60,
        'medio',
        'interno',
        ARRAY['Papel','Feijões','Cola branca','Lápis'],
        ARRAY['Coordenação Motora','Foco','Paciência'],
        ARRAY['Desenhe forma simples (círculo, coração)','Passe cola na linha','Criança cola feijões um a um','Aguarde secar','Admire o resultado juntos'],
        ARRAY['Desenvolve pinça fina','Requer atenção sustentada','Treina controle de movimento delicado']
    ),
(
        'atividade_034',
        'Caminhada de pés descalços na calçada',
        'Andar descalço em superfícies variadas (grama, calçada, terra) estimula sensores dos pés.',
        'ao ar livre',
        'media',
        1,
        15,
        36,
        60,
        'facil',
        'ao ar livre',
        ARRAY['Nenhum'],
        ARRAY['Exploração Sensorial','Equilíbrio','Propriocepção'],
        ARRAY['Escolha local seguro (quintal, calçada)','Tire sapatos da criança','Caminhem juntos descalços','Conversem sobre texturas sentidas','Varie superfícies se possível'],
        ARRAY['Supervisione para evitar objetos perigosos','Estimula terminações nervosas dos pés','Melhora propriocepção e equilíbrio']
    ),
(
        'atividade_035',
        'Coleção de folhas do quarteirão',
        'Caminhar coletando folhas diferentes e depois classificar por tamanho, forma ou cor.',
        'ao ar livre',
        'media',
        2,
        20,
        36,
        96,
        'facil',
        'ao ar livre',
        ARRAY['Sacola ou caixinha'],
        ARRAY['Observação','Classificação','Conexão com Natureza'],
        ARRAY['Dê sacola para criança','Caminhem coletando folhas variadas','Voltem para casa','Separem por categorias','Conversem sobre diferenças'],
        ARRAY['Ensine respeito pela natureza','Classificação é base da ciência','Pode colar folhas em papel depois']
    ),
(
        'atividade_036',
        'Desenhar sombras no chão',
        'Em dia ensolarado, traçar contorno da sombra de objetos ou do próprio corpo no chão.',
        'ao ar livre',
        'media',
        3,
        15,
        48,
        96,
        'medio',
        'ao ar livre',
        ARRAY['Giz','Dia ensolarado'],
        ARRAY['Observação','Ciência','Criatividade'],
        ARRAY['Escolha local com sol forte','Coloque objeto no chão','Contorne sombra com giz','Converse sobre luz e sombra','Tente em horários diferentes'],
        ARRAY['Introduz conceitos de física','Sombra muda conforme sol','Estimula curiosidade científica']
    ),
(
        'atividade_037',
        'Observando céu e contando nuvens',
        'Deitar no chão e olhar nuvens, identificar formas e contar quantas conseguem ver.',
        'ao ar livre',
        'baixa',
        1,
        10,
        24,
        60,
        'facil',
        'ao ar livre',
        ARRAY['Toalha ou colchonete'],
        ARRAY['Imaginação','Linguagem','Atenção'],
        ARRAY['Escolha local seguro ao ar livre','Deitem confortavelmente','Olhem o céu juntos','Pergunte: com o que parecem as nuvens?','Contem quantas veem'],
        ARRAY['Momento calmo de conexão','Estimula linguagem descritiva','Desenvolve imaginação']
    ),
(
        'atividade_038',
        'Afunda ou boia?',
        'Bacia com água e objetos variados. Criança prevê se vai afundar ou boiar e testa.',
        'ao ar livre',
        'media',
        5,
        15,
        36,
        72,
        'facil',
        'ao ar livre',
        ARRAY['Bacia com água','Objetos variados (pedra, rolha, colher)'],
        ARRAY['Raciocínio Lógico','Ciência','Observação'],
        ARRAY['Encha bacia com água','Separe objetos diversos','Pergunte: vai afundar ou boiar?','Criança faz previsão','Testem juntos'],
        ARRAY['Introduz método científico','Hipótese → teste → resultado','Não dê respostas antes do teste']
    ),
(
        'atividade_039',
        'Plantar feijão no algodão',
        'Colocar feijão em algodão úmido e acompanhar germinação dia a dia.',
        'ao ar livre',
        'baixa',
        5,
        5,
        36,
        96,
        'facil',
        'interno',
        ARRAY['Feijão','Algodão','Potinho transparente','Água'],
        ARRAY['Responsabilidade','Paciência','Ciência'],
        ARRAY['Coloque algodão no pote','Umedeça com água','Coloque feijão sobre algodão','Deixe em local com luz','Observe crescimento diariamente'],
        ARRAY['Ensina ciclo de vida','Desenvolve cuidado com ser vivo','Requer constância (regar)']
    ),
(
        'atividade_040',
        'Fazer chuva com garrafa furada',
        'Furar garrafa plástica, encher de água e criar chuva artificial para regar plantas.',
        'ao ar livre',
        'media',
        5,
        10,
        24,
        48,
        'facil',
        'ao ar livre',
        ARRAY['Garrafa plástica','Prego para furar','Água'],
        ARRAY['Ciência','Coordenação Motora','Cuidado'],
        ARRAY['Adulto fura garrafa (vários furinhos)','Encha de água','Criança segura de cabeça para baixo','Água sai como chuva','Use para regar plantas'],
        ARRAY['Explica fluxo de água','Integra brincadeira com cuidado','Ideal para dias quentes']
    ),
(
        'atividade_041',
        'Seguir caminho de fita no chão',
        'Cole fita colorida no chão fazendo caminho. Criança anda sobre a linha sem sair.',
        'movimento',
        'media',
        5,
        10,
        36,
        60,
        'facil',
        'interno',
        ARRAY['Fita crepe colorida'],
        ARRAY['Equilíbrio','Foco','Coordenação Motora'],
        ARRAY['Cole fita fazendo linha no chão','Pode fazer curvas e ziguezagues','Criança caminha sobre a linha','Incentive não sair da linha','Aumente dificuldade: andar de costas'],
        ARRAY['Atividade Montessori de linha','Desenvolve controle motor','Pode fazer com olhos fechados (avançado)']
    ),
(
        'atividade_042',
        'Organizar roupas por tipo',
        'Separar roupas limpas por categoria: camisas, calças, meias. Vida prática que ensina classificação.',
        'cognitiva',
        'baixa',
        2,
        10,
        24,
        48,
        'facil',
        'interno',
        ARRAY['Roupas limpas','Cestas ou pilhas'],
        ARRAY['Classificação','Autonomia','Colaboração'],
        ARRAY['Tire roupas do varal','Mostre categorias: camisas, calças','Peça criança separar','Nomeie cada peça','Agradeça pela ajuda'],
        ARRAY['Montessori vida prática','Integra criança nas tarefas domésticas','Ensina responsabilidade']
    ),
(
        'atividade_043',
        'Eco de sons na casa',
        'Você faz som (palma, assobio), criança repete. Desenvolve imitação e ritmo.',
        'criativa',
        'baixa',
        0,
        10,
        24,
        48,
        'facil',
        'interno',
        ARRAY['Nenhum'],
        ARRAY['Ritmo','Memória','Atenção'],
        ARRAY['Faça som simples (2 palmas)','Peça criança repetir','Aumente complexidade gradualmente','Inverta: criança faz, você repete','Tente sequências de 3-4 sons'],
        ARRAY['Desenvolve memória auditiva','Base para linguagem oral','Pode usar instrumentos caseiros']
    ),
(
        'atividade_044',
        'Procure objeto enquanto arrumo casa',
        'Pedir para criança encontrar objeto específico enquanto você arruma. Integra ajuda com jogo.',
        'cognitiva',
        'media',
        0,
        10,
        36,
        72,
        'medio',
        'interno',
        ARRAY['Objetos da casa'],
        ARRAY['Foco','Memória','Colaboração'],
        ARRAY['Nomeie objeto específico','Dê dica de localização','Criança procura enquanto você trabalha','Comemore quando encontrar','Repita com outro objeto'],
        ARRAY['Integra rotina com brincadeira','Desenvolve atenção seletiva','Criança sente-se útil']
    ),
(
        'atividade_045',
        'Trilha de tampas para carrinhos',
        'Organizar tampas no chão como pista. Criança empurra carrinho seguindo o caminho.',
        'movimento',
        'media',
        5,
        15,
        36,
        60,
        'medio',
        'interno',
        ARRAY['Tampas plásticas','Carrinho pequeno'],
        ARRAY['Coordenação Motora','Planejamento','Criatividade'],
        ARRAY['Coloque tampas enfileiradas no chão','Crie curvas e obstáculos','Dê carrinho para criança','Peça para seguir trilha','Deixe ela criar própria trilha depois'],
        ARRAY['Desenvolve planejamento espacial','Controle motor fino ao guiar carrinho','Pode complicar adicionando túneis']
    ),
(
        'atividade_046',
        'Caminhar carregando potes com água',
        'Criança caminha pela casa carregando pote com água sem derramar. Montessori clássico.',
        'movimento',
        'media',
        2,
        10,
        48,
        96,
        'medio',
        'interno',
        ARRAY['Potinho com água','Pano para limpar'],
        ARRAY['Equilíbrio','Foco','Paciência'],
        ARRAY['Encha pote até metade','Peça criança levar até outro local','Desafio: não derramar','Se derramar, ela limpa (vida prática)','Comemore sucesso'],
        ARRAY['Atividade Montessori de concentração','Desenvolve controle corporal refinado','Consequência natural ensina cuidado']
    ),
(
        'atividade_047',
        'Passar pano dançando',
        'Colocar música e passar pano no chão dançando. Transforma tarefa em diversão.',
        'movimento',
        'alta',
        2,
        10,
        36,
        72,
        'facil',
        'interno',
        ARRAY['Pano úmido','Música'],
        ARRAY['Coordenação Motora','Colaboração','Ritmo'],
        ARRAY['Coloque música animada','Dê pano para criança','Passem pano dançando juntos','Faça movimentos divertidos','Celebre chão limpo'],
        ARRAY['Atividade física + tarefa doméstica','Criança não sente como obrigação','Fortalece senso de contribuição']
    ),
(
        'atividade_048',
        'Eco de palavras na janela',
        'Falar palavras por sílabas (BO-LA) e criança repete. Desenvolve consciência silábica.',
        'criativa',
        'baixa',
        0,
        10,
        48,
        84,
        'medio',
        'interno',
        ARRAY['Nenhum'],
        ARRAY['Linguagem','Consciência Fonológica','Memória'],
        ARRAY['Escolha palavra simples (casa)','Fale separando sílabas: CA-SA','Criança repete','Bata palmas para cada sílaba','Aumente dificuldade gradualmente'],
        ARRAY['Base essencial da alfabetização','Comece com 2 sílabas','Pode usar nomes da família']
    ),
(
        'atividade_049',
        'Sentir cheiros da cozinha',
        'Vendar olhos e apresentar cheiros diferentes para criança identificar pelo olfato.',
        'sensorial',
        'baixa',
        3,
        10,
        12,
        36,
        'facil',
        'interno',
        ARRAY['Vendas ou fechar olhos','Alimentos aromáticos (laranja, café, canela)'],
        ARRAY['Exploração Sensorial','Discriminação','Foco'],
        ARRAY['Feche olhos da criança suavemente','Aproxime alimento aromático','Pergunte: o que você sente?','Deixe ela adivinhar','Abra olhos e confirme'],
        ARRAY['Evite cheiros fortes/irritantes','Material sensorial Montessori','Desenvolve discriminação olfativa']
    ),
(
        'atividade_050',
        'Linha do tempo do meu dia',
        'Desenhar linha horizontal e marcar as atividades do dia em ordem. Desenvolve noção temporal.',
        'cognitiva',
        'baixa',
        3,
        20,
        60,
        96,
        'medio',
        'interno',
        ARRAY['Papel comprido','Lápis','Régua (opcional)'],
        ARRAY['Memória','Organização Temporal','Linguagem'],
        ARRAY['Desenhe linha horizontal','Pergunte: o que fez desde que acordou?','Desenhe símbolo para cada atividade','Coloque em ordem na linha','Leia história do dia juntos'],
        ARRAY['Desenvolve sequência temporal','Base para narrativa escrita','Pode incluir horários aproximados']
    )
ON CONFLICT (codigo_externo) DO UPDATE SET
    titulo = EXCLUDED.titulo,
    descricao = EXCLUDED.descricao,
    categoria = EXCLUDED.categoria,
    energia = EXCLUDED.energia,
    preparo_minutos = EXCLUDED.preparo_minutos,
    duracao_minutos = EXCLUDED.duracao_minutos,
    idade_min_meses = EXCLUDED.idade_min_meses,
    idade_max_meses = EXCLUDED.idade_max_meses,
    dificuldade = EXCLUDED.dificuldade,
    local = EXCLUDED.local,
    materiais = EXCLUDED.materiais,
    beneficios = EXCLUDED.beneficios,
    passos = EXCLUDED.passos,
    dicas = EXCLUDED.dicas;
