-- Novas atividades sensoriais (atividade_051 a atividade_056)
-- Cobertura: 0-12 meses, 6-18 meses, 18-36 meses, 36-60 meses (x2), 48-96 meses

INSERT INTO brincareducando.atividades (
    codigo_externo,
    titulo,
    descricao,
    categoria,
    energia,
    preparo_minutos,
    duracao_minutos,
    idade_min_meses,
    idade_max_meses,
    dificuldade,
    local,
    materiais,
    beneficios,
    passos,
    dicas
) VALUES
(
    'atividade_051',
    'Massagem com flanela macia',
    'Friccionar suavemente flanela e retalhos de diferentes texturas no corpo do bebê, nomeando cada parte tocada com voz calma.',
    'sensorial',
    'baixa',
    2,
    10,
    0,
    12,
    'facil',
    'interno',
    ARRAY['Flanela macia','Retalho de veludo','Toalha pequena de algodão'],
    ARRAY['Consciência Corporal','Vínculo Afetivo','Exploração Sensorial'],
    to_jsonb(ARRAY['Deite o bebê de costas num lugar macio','Pegue a flanela e friccione suavemente no braço','Nomeie a parte do corpo tocada: aqui é o bracinho','Troque para textura diferente e repita','Observe reações — se bebê recuar, pause e acolha']),
    ARRAY['Toque gentil é linguagem de vínculo para bebês','Evite fricção forte — sensação deve ser prazerosa','Repetir rotineiramente cria segurança corporal']
),
(
    'atividade_052',
    'Bolhas de sabão para tocar',
    'Soprar bolhas de sabão e incentivar o bebê a perseguir, tocar e estourar cada uma, explorando textura efêmera e movimento.',
    'sensorial',
    'media',
    2,
    10,
    6,
    18,
    'facil',
    'interno',
    ARRAY['Pote de bolhas de sabão (água + detergente neutro)','Varinha caseira (arame dobrado ou canudo)'],
    ARRAY['Exploração Sensorial','Coordenação Motora','Percepção Visual'],
    to_jsonb(ARRAY['Prepare mistura de água e detergente neutro','Sente criança em tapete ou chão seguro','Sopre bolhas em direção a ela devagar','Incentive tocar com o dedinho','Comemore cada bolha estourada com expressão animada']),
    ARRAY['Bolhas ensinam causa e efeito de forma concreta','Detergente neutro é seguro se tocar boca','Movimento lento das bolhas estimula rastreamento visual']
),
(
    'atividade_053',
    'Frutas na palma da mão',
    'Explorar pedaços de frutas com texturas contrastantes — liso, rugoso, macio, firme — usando tato, olfato e paladar juntos.',
    'sensorial',
    'baixa',
    5,
    15,
    18,
    36,
    'facil',
    'interno',
    ARRAY['3 frutas variadas (banana, maçã, uva ou similar)','Prato pequeno','Toalha de mão'],
    ARRAY['Exploração Sensorial','Linguagem','Discriminação Tátil'],
    to_jsonb(ARRAY['Corte frutas em pedaços seguros','Coloque uma fruta por vez na mão da criança','Pergunte: é liso ou rugoso? Macio ou duro?','Incentive cheirar antes de comer','Nomeie textura, cheiro e sabor juntos']),
    ARRAY['Associar palavras a sensações acelera vocabulário sensorial','Apresentar frutas novas reduz neofobia alimentar','Exploração multissensorial precede aceitação alimentar']
),
(
    'atividade_054',
    'Caixa do toque misterioso',
    'Enfiar a mão numa caixa fechada e adivinhar o objeto escondido só pelo tato, sem espiar.',
    'sensorial',
    'baixa',
    5,
    15,
    36,
    60,
    'facil',
    'interno',
    ARRAY['Caixa de sapatos','Tesoura (adulto)','5-6 objetos domésticos variados (colher, bola, esponja, chave)'],
    ARRAY['Discriminação Tátil','Vocabulário','Raciocínio Lógico'],
    to_jsonb(ARRAY['Faça furo na tampa da caixa grande o suficiente para a mão','Coloque um objeto dentro sem mostrar','Peça criança enfiar a mão e descrever o que sente','Faça perguntas: é duro? redondo? frio?','Deixe ela adivinhar e depois abrir para conferir']),
    ARRAY['Atividade clássica Montessori de refinamento tátil','Descrever antes de adivinhar expande vocabulário sensorial','Aumente dificuldade com objetos de formas mais próximas']
),
(
    'atividade_055',
    'Pintura com os pés',
    'Mergulhar os pés em tinta lavável e caminhar sobre papel grande no chão, deixando rastros coloridos.',
    'sensorial',
    'alta',
    10,
    15,
    36,
    60,
    'facil',
    'interno',
    ARRAY['Tinta guache lavável','Papel grande (kraft ou jornal)','Bacia com água para lavar','Toalha'],
    ARRAY['Exploração Sensorial','Coordenação Motora','Expressão'],
    to_jsonb(ARRAY['Estenda papel grande no chão e fixe com fita','Coloque tinta numa bandeja rasa','Ajude criança a mergulhar um pé por vez','Deixe caminhar e explorar livremente sobre o papel','Ao terminar, lave pés na bacia e converse sobre as cores']),
    ARRAY['Pés têm alta densidade de receptores táteis','Tinta guache sai facilmente da pele com água','Fotografe — a obra vira lembrança afetiva especial']
),
(
    'atividade_056',
    'Jardineiro descalço',
    'Caminhar descalço em superfícies variadas ao ar livre — grama, terra, pedra lisa — explorando cada sensação com atenção plena.',
    'sensorial',
    'media',
    2,
    20,
    48,
    96,
    'facil',
    'ao ar livre',
    ARRAY['Quintal ou praça','Superfícies variadas (grama, terra, calçada lisa, areia)'],
    ARRAY['Propriocepção','Equilíbrio','Consciência Corporal'],
    to_jsonb(ARRAY['Escolha área segura sem vidros ou espinhos','Tire os sapatos junto com a criança','Andem devagar em cada superfície','Pergunte: o que você sente agora? É diferente da grama?','Encerrem sentados descalços conversando sobre as sensações']),
    ARRAY['Andar descalço fortalece musculatura plantar e equilíbrio','Contato com terra ativa o sistema nervoso parassimpático','Fundamento da pedagogia da natureza (forest school)']
)
ON CONFLICT (codigo_externo) DO UPDATE SET
    titulo = EXCLUDED.titulo,
    descricao = EXCLUDED.descricao,
    categoria = EXCLUDED.categoria,
    energia = EXCLUDED.energia,
    preparo_minutos = EXCLUDED.preparo_minutos,
    duracao_minutos = EXCLUDED.duracao_minutos,
    idade_min_meses = EXCLUDED.idade_min_meses,
    idade_max_meses = EXCLUDED.idade_max_meses,
    dificuldade = EXCLUDED.dificuldade,
    local = EXCLUDED.local,
    materiais = EXCLUDED.materiais,
    beneficios = EXCLUDED.beneficios,
    passos = EXCLUDED.passos,
    dicas = EXCLUDED.dicas;
